{% set version = "4.1.89a" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/rsgislib/archive/{{ version }}.tar.gz
  sha256: d78007f86f495dd5abf07c09e4d01221886f5cfa0796ee8b3b976151b609028b

build:
  number: 1
  # CGAL etc do not support earlier than vc14
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - hdf5
    - h5py
    - xerces-c
    - muparser
    - gsl
    - geos 3.7.2
    - gdal >=3.0.1
    - boost-cpp
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal-cpp 4.14
    - tqdm
    - rios
  run:
    - python
    - hdf5
    - h5py
    - xerces-c
    - muparser
    - gsl
    - geos 3.7.2
    - gdal >=3.0.1
    - boost-cpp
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal-cpp 4.14
    - tqdm
    - rios

test:
  source_files:
    - python_tests
  commands:
    # Random crashing under Windows. Skip for now
    - cd python_tests/RSGISLibTests && python RSGIStests.py --all  # [not win]
  imports:
    - rsgislib
    - rsgislib.imagecalibration
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagefilter
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.segmentation
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    # get a memory error here - must investigate
    #- rsgislib.histocube
    - rsgislib.imagemorphology

about:
  home: http://www.rsgislib.org
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
