{% set version = "3.5.8" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://bitbucket.org/petebunting/rsgislib/downloads/rsgislib-{{ version }}.tar.gz
  sha256: 66e7abe2977d1e3a9de6dc667c8ba666666ca365d49f3b473748afd0d75270ff
  patches:
    # boost libs have changed their names recently
    - winboost.patch  # [win]

build:
  number: 0
  # CGAL etc do not support earlier than vc14
  skip: True  # [win and py<35]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - hdf5 1.10.*
    - xerces-c 3.2.*
    - muparser
    - gsl 2.4
    - geos 3.6.2
    - gdal 2.3.*
    - boost-cpp 1.66.*
    - kealib 1.4.*
    - cgal 4.12
    - python
    - vc   9  # [win and py27]
    - vc  14  # [win and (py35 or py36)]
  run:
    - hdf5 1.10.*
    - xerces-c 3.2.*
    - muparser
    - gsl 2.4
    - geos 3.6.2
    - gdal 2.3.*
    - boost-cpp 1.66.*
    - kealib 1.4.*
    - cgal 4.12
    - python
    - vc   9  # [win and py27]
    - vc  14  # [win and (py35 or py36)]

test:
  source_files:
    - python_tests
  commands:
    - cd python_tests/RSGISLibTests && python RSGIStests.py --all
    # These are timming out :-(
    # - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    # - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - rsgislib
    - rsgislib.imagecalibration
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagefilter
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.segmentation
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    # get a memory error here - must investigate
    #- rsgislib.histocube
    - rsgislib.imagemorphology

about:
  home: http://www.rsgislib.org
  license: GPL3
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
