{% set version = "5.0.3" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/rsgislib/archive/refs/tags/{{ version }}.tar.gz
  sha256: fbe073b46365e9d8f6882e14b2d6bb8316d3c6e6282e55a8441becf3f9541561

build:
  number: 2

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - hdf5
    - muparser
    - gsl
    - gdal
    - boost-cpp
    - kealib
    - tqdm
  run:
    - python
    - hdf5
    - h5py
    - muparser
    - gsl
    - gdal
    - boost-cpp
    - kealib
    - tqdm
    - rios

test:
  requires:
    - pytest
    - scipy
  source_files:
    - python_tests
  commands:
    - pytest python_tests
  imports:
    - rsgislib
    - rsgislib.changedetect
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagecalibration
    - rsgislib.imagefilter
    - rsgislib.imagemorphology
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.regression
    - rsgislib.segmentation
    - rsgislib.timeseries
    - rsgislib.tools
    - rsgislib.vectorattrs
    - rsgislib.vectorgeoms
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    

about:
  home: http://www.rsgislib.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
