{% set version = "5.1.8" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  git_url: https://github.com/remotesensinginfo/rsgislib.git
  git_tag: main

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - hdf5
    - muparser
    - gsl
    - gdal
    - libboost-devel
    - kealib
    - tqdm
  run:
    - python
    - numpy
    - hdf5
    - h5py
    - muparser
    - gsl
    - gdal
    - kealib
    - tqdm
    - rios
    - libgdal-kea

test:
  requires:
    - pytest
    - scipy
    - matplotlib
    - libgdal-kea
    - geopandas
  source_files:
    - python_tests
  commands:
    - pytest python_tests # [not win]
  imports:
    - rsgislib
    - rsgislib.changedetect
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagecalibration
    - rsgislib.imagefilter
    - rsgislib.imagemorphology
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.regression
    - rsgislib.segmentation
    - rsgislib.timeseries
    - rsgislib.tools
    - rsgislib.vectorattrs
    - rsgislib.vectorgeoms
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    

about:
  home: http://www.rsgislib.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
