{% set version = "3.6.14" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://bitbucket.org/petebunting/rsgislib/downloads/rsgislib-{{ version }}.tar.gz
  sha256: f301fc88855bd55eaaef6386dbec9290dcdf74c93b2e74ef3f9311d887b78c82
  patches:
    # Seem to need this patch so the proper includes are used
    - geosinline.patch
    - osxpythonlinking.patch  # [osx]

build:
  number: 5
  # CGAL etc do not support earlier than vc14
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - hdf5
    - xerces-c
    - muparser
    - gsl
    - geos
    - gdal
    - boost-cpp
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal-cpp
  run:
    - python
    - hdf5
    - xerces-c
    - muparser
    - gsl
    - geos
    - gdal
    - boost-cpp
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal-cpp

test:
  source_files:
    - python_tests
  commands:
    # Random crashing under Windows. Skip for now
    - cd python_tests/RSGISLibTests && python RSGIStests.py --all  # [not win]
  imports:
    - rsgislib
    - rsgislib.imagecalibration
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagefilter
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.segmentation
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    # get a memory error here - must investigate
    #- rsgislib.histocube
    - rsgislib.imagemorphology

about:
  home: http://www.rsgislib.org
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
