{% set version = "5.0.13" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/rsgislib/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9b5ac3f9b8da7fb4af95e4f828420881bab43bc7b21e9ccdce53dcad4b394477

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - hdf5
    - muparser
    - gsl
    - gdal
    - boost-cpp
    - kealib
    - tqdm
  run:
    - python
    - numpy
    - hdf5
    - h5py
    - muparser
    - gsl
    - gdal
    - boost-cpp
    - kealib
    - tqdm
    - rios

test:
  requires:
    - pytest
    - scipy
    - matplotlib
  source_files:
    - python_tests
  commands:
    - pytest python_tests
  imports:
    - rsgislib
    - rsgislib.changedetect
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagecalibration
    - rsgislib.imagefilter
    - rsgislib.imagemorphology
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.regression
    - rsgislib.segmentation
    - rsgislib.timeseries
    - rsgislib.tools
    - rsgislib.vectorattrs
    - rsgislib.vectorgeoms
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    

about:
  home: http://www.rsgislib.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
