travis:
  secure:
    BINSTAR_TOKEN: TBtU7wm9Ay2h6SYTmuwWpP95ZqY2XS6dV3P5d4Sb7jrQRF8tC+KNOT5hwsjY1wbKvukGwO+wOOwP6CsZg2snVADfHSHf7Px1OLEFRqnbaN5+CIm1lQTb/kgEUAzgyGmmOYgT0Qp0R1ZJxvRg0q6ISfLCG9FQgXWRVVTYXfjpxwhy62aH9c8Srseb6PZV7n2kM/SHplT8bMb4p1xFE7WsqwT0h5R2O4RmQYK9e0sjEcdl7Zs6XmsMZDLA4orBDYsFG4zVcTcnofKdkwVXF8pGxZ1P6ock3PZ/jLAIxbMEZkKEP94/nNFuLCQU9BOvgu7YqXqnLmfOzLvQTPoHyRxQtzUWWBhpBufUN2vUXAJmf0P/ghgVTmT/SA9W38xjbv30L9eVSruWrGP3dGtVLUQHvGKa/sIpj63LGbGhglo4cyB5bnLAqwx8Uun/ffT0Y0+0wY4ey/wYgbg8xzyb2oDPxyNNCLTOEWZZThF87JOsalyRZIwFHmWD83U7dzHZEHzEFj1SRskccp60xDRh/Puc/49pmZnTW3ERVlHF/0RvAN3XRdtIkrqZMjwLXaq1jWIAn3aWPFq4z3fbgHbj+fjwjtahf6fgjONB3DKyip0Xxhey31VndOa6fAarJ/3uP6oheWHpB1kEAGOlTwIC2bzEkUV3MtPqYC3H+mxt9A7QsEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
