travis:
  secure:
    BINSTAR_TOKEN: FqbSV1MbAD73sDkslBwI09Db8gMn5k1OoArtKluJ0T418RsHcpIR7IqH00EQc40DqRD3tca6I2oFJ19Yexr7VSQ55RhKI04p9fpH8mkCAgLSCr/u7W9fAPI2cIfwEswTiOXySiuN+DmAnfgPQqFoFQ+q+EChUgNxron7VE5huagPtPrDZFObW+QF5/qPn3Jt0rS4Wof5rZaeDG4HS1NuqdS0X5NRQC+CG+kQ/9LpMg5lX6ipA+YJPVZihzvEnbwxogU9I4iP+1pxKCRvAxSS7UXnoSN557seoFfufSHLXjTLcTAQ2OpaCkny3xk2H+CJfvz9Mh3BjD9ItSEHhZ0v97lolo5hP1cwNQRACL9TXL84HWoKA3ZOxMxLQYFQCuCL0Umqc+VPw5nM2Rz+OMe1yFpwZXhm91qrWzVhvWJe9ywdWpFh5RCI7Pa1rShJRyw76GmVZRnrGij4QgfItRV9FG0DiszxOJqJxpxjqJppSa52sNIKZOG4y7jbiOxmqUKCR+kgJpO6fCluHcDVh/jTv3OxnbRswG3oe9xRJ9jx59y1JcJlnyllSbYilORHrT7Wve0sW1QYTGhwbWUmRwFnsFKNuF7lwkqRmyC5M5YbyykW4f2u1LnIx8wGV2wIpDIFTyBs2YchOVKADJFB3lBDUe1fVSfnDkd1WZTMBL6q9QU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
